export enum EAppRoutes {
  DASHBOARD = "/dashboard",
  PROFILE = "/profile",
  WALLET = "/wallet",
  MESSAGES = "/messages",
  CALLS = "/calls",
  SETTINGS = "/settings",
  LOGIN = "/login",
  SIGNUP = "/signup",
  INVITATION = "/invitation",
  HOME = "/",
  STUDENT = "/student",
  FORGOT_PASSWORD = "/forgot-password",
  VERIFY_TOKEN = "/verify-token",
  VERIFICATION_MESSAGE = "/verification-message",
  RESET_PASSWORD = "/reset-password",
  PASSWORD_RESET_MESSAGE = "/password-reset-message",
  PAYMENT_SUCCESS = "/payment/success",
  PAYMENT_CANCEL = "/payment/cancel",
  PAYMENT_FAILED = "/payment/failed",
  RESET_EMAIL_FAILED = "/email-reset/failed",
  RESET_EMAIL_SUCCESS = "/email-reset/success",
  RESET_EMAIL_ALERT = "/email-reset/alert",
}

export enum EAppQueryParamsKey {
  SEARCH = "search",
  SEARCH_V2 = "q",
  PAGE = "page",
  ORDER_BY = "order_by",
  ORDER_BY_V2 = "orderBy",
  SORT_BY_V2 = "sortBy",
  SORT_BY = "sort_by",
  SORT_ORDER = "sortOrder",
  FILTER = "filter",
  FILTER_V2 = "features",
  FILTER_V3 = "status",
  REDIRECT_URL = "redirect_url",
  PAGE_SIZE = "pageSize",
  DOMAIN = "domain",
  TAB = "tab",
}
